# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [3]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
array_2 = array.reshape(2, 5)
print(array_2)

[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [6]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
reversed_arr = np.flip(arr)
print(reversed_arr)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [8]:
even_numbers = arr[arr % 2 == 0]
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [9]:
array = np.arange(9).reshape(3, 3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [10]:
random_array = np.random.randint(0, 100, size=(4,3,2))
print(random_array)

[[[11 74]
  [21 89]
  [ 5 73]]

 [[28 49]
  [ 2 84]
  [22 85]]

 [[41 36]
  [79 67]
  [50 96]]

 [[34  8]
  [65 19]
  [82  3]]]


In [11]:
print(np.min(random_array))
print(np.max(random_array))

2
96


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [13]:
A = np.random.rand(6, 4)
B = np.random.rand(4, 3)
C = np.dot(A, B)
print(A)
print(B)
print(C)

[[0.51568747 0.47088906 0.36456783 0.62936825]
 [0.28647332 0.55009614 0.19763301 0.28135199]
 [0.04609145 0.39067504 0.15483124 0.06104847]
 [0.98272999 0.32495268 0.96238802 0.44128713]
 [0.62746207 0.56126923 0.98553779 0.78272039]
 [0.00492502 0.02401655 0.33982192 0.58976919]]
[[0.12796323 0.81272256 0.20219357]
 [0.57565397 0.31517325 0.34651442]
 [0.63470897 0.19892249 0.48747196]
 [0.66964372 0.89975703 0.46389796]]
[[0.98990516 1.20632172 0.73711779]
 [0.66716811 0.698661   0.47539847]
 [0.36994515 0.24631809 0.24849007]
 [1.21915507 1.48959504 0.98515185]
 [1.5530624  1.58715343 1.16488111]
 [0.6250787  0.60981924 0.44856427]]


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [14]:
array = np.random.rand(7, 7)
print(array)

[[0.0397074  0.9203089  0.52998163 0.50250811 0.46282962 0.05258502
  0.54931016]
 [0.96572996 0.41779072 0.34798239 0.10494709 0.66244276 0.35731705
  0.07065637]
 [0.59598774 0.08477499 0.66944067 0.7978476  0.2307143  0.83323763
  0.5101569 ]
 [0.49459796 0.64757752 0.42634872 0.44095187 0.35018505 0.95386497
  0.5158955 ]
 [0.32854811 0.44659671 0.55671109 0.19667302 0.14642302 0.77794182
  0.6785382 ]
 [0.604492   0.89275399 0.40137799 0.55726783 0.74446475 0.28075898
  0.32490694]
 [0.72904288 0.63206149 0.22527406 0.73356195 0.05959706 0.64859176
  0.76657058]]


In [15]:
mean_array = np.mean(array)
std_array = np.std(array)
print(mean_array)
print(std_array)

0.4952618944918106
0.2528884413056164


In [16]:
arr = array * 10
normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
print(normalized)

[[0.         0.95095037 0.52944092 0.49977261 0.45692431 0.01390637
  0.55031355]
 [1.         0.40828738 0.33290224 0.07045151 0.67248401 0.34298262
  0.0334214 ]
 [0.60072008 0.04866792 0.68004095 0.81870597 0.20626592 0.85692321
  0.50803244]
 [0.49123054 0.65643122 0.41752905 0.43329881 0.33528087 0.98718715
  0.51422948]
 [0.31191542 0.4393946  0.55830572 0.16950517 0.11524084 0.79720997
  0.68986526]
 [0.60990372 0.92119418 0.39056348 0.55890694 0.76105852 0.26030854
  0.30798335]
 [0.74440462 0.63967566 0.20039108 0.74928472 0.02147858 0.65752649
  0.78493032]]


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [2]:
import pandas as pd
import matplotlib
import seaborn as sns

### Загрузите датасет Tips из набора датасетов seaborn

In [8]:
tips = pd.read_csv('tips.csv')

### Посмотрите на первые 5 строчек

In [9]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


### Узнайте сколько всего строчек и колонок в данных

In [10]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


### Проверьте есть ли пропуски в данных

In [12]:
tips.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

### Посмотрите на распределение числовых признаков

In [13]:
tips.describe()

,total_bill,tip,size
count,244.000000,244.000000,244.000000
mean,19.785943,2.998279,2.569672
std,8.902412,1.383638,0.951100
min,3.070000,1.000000,1.000000
25%,13.347500,2.000000,2.000000
50%,17.795000,2.900000,2.000000
75%,24.127500,3.562500,3.000000
max,50.810000,10.000000,6.000000


### Найдите максимальное значение 'total_bill'

In [17]:
print(tips['total_bill'].max())

50.81


### Найдите количество курящих людей

In [26]:
print((tips['smoker'] == 'Yes').sum())

93


### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [28]:
print(tips.groupby('day')['total_bill'].mean())

day
Fri     17.151579
Sat     20.441379
Sun     21.410000
Thur    17.682742
Name: total_bill, dtype: float64


### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [31]:
median_bill = tips['total_bill'].median()
print(median_bill)
high_bill = tips[tips['total_bill'] > median_bill]
tip_by_sex = high_bill.groupby('sex')['tip'].mean()
print(tip_by_sex)

17.795
sex
Female    3.663939
Male      3.756404
Name: tip, dtype: float64


### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [32]:
tips['smoker_binary'] = tips['smoker'].map({'No': 0, 'Yes': 1})

In [40]:
tips.iloc[80:100]

,total_bill,tip,sex,smoker,day,time,size,smoker_binary
80,19.44,3.00,Male,Yes,Thur,Lunch,2,1
81,16.66,3.40,Male,No,Thur,Lunch,2,0
82,10.07,1.83,Female,No,Thur,Lunch,1,0
83,32.68,5.00,Male,Yes,Thur,Lunch,2,1
84,15.98,2.03,Male,No,Thur,Lunch,2,0
85,34.83,5.17,Female,No,Thur,Lunch,4,0
86,13.03,2.00,Male,No,Thur,Lunch,2,0
87,18.28,4.00,Male,No,Thur,Lunch,2,0
88,24.71,5.85,Male,No,Thur,Lunch,2,0
89,21.16,3.00,Male,No,Thur,Lunch,2,0


# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ